name: "Pytest Validation"
description: "Validate source code running pytest"
inputs:
  paths-to-ignore:
    description: "Folders and or files to ignore. Provide a comma separated list of 
      paths from the current directory. Any file under these paths will be ignored. 
      Example: 'examples,core/scrap,setup.py'"
    required: false
  skip-doctests:
    description: "Skip doctests"
    required: false
  pytest-args:
    description: "Additional arguments to pass to pytest"
    required: false
    default: "-v"
runs:
  using: 'composite'
  steps:
    - name: Install Dependencies
      uses: i2mint/isee/actions/install-packages@master
      with:
        pypi-packages: 'pytest'

    - name: Validate Source Code
      shell: bash
      run: |
        if [ -n "${{ inputs.paths-to-ignore }}" ]; then
          IFS=',' read -ra paths <<< "$paths-to-ignore"
          options="${{ inputs.pytest-args }}"
          for path in "${paths[@]}"
          do
              options+=" --ignore=./$path"
          done
        fi
        if [ "${{ inputs.skip-doctests }}" == "true" ]; then
          options+=" --doctest-modules"
        fi
        pytest $options .
