name: "Pytest Validation"
description: "Validate source code running pytest"
inputs:
  root-dir:
    description: "Root directory to validate. Defaults to the current directory."
    required: false
    default: "."
  paths-to-ignore:
    description: "Folders and or files to ignore. Provide a comma separated list of 
      paths from the current directory. Any file under these paths will be ignored. 
      Example: 'examples,core/scrap,setup.py'"
    required: false
  skip-doctests:
    description: "Skip doctests"
    required: false
  pytest-args:
    description: "Additional arguments to pass to pytest"
    required: false
    default: "-v"
runs:
  using: 'composite'
  steps:
    - name: Install Dependencies
      uses: i2mint/isee/actions/install-packages@master
      with:
        pypi-packages: 'pytest'

    - name: Validate Source Code
      shell: bash
      run: |
        set -e
        options="${{ inputs.pytest-args }}"
        if [ -n "${{ inputs.paths-to-ignore }}" ]; then
          IFS=',' read -ra paths <<< "${{ inputs.paths-to-ignore }}"
          for path in "${paths[@]}"
          do
              # First try the path as a module
              options+=" --ignore-glob=${{ inputs.root-dir }}/$path.py"
              # Then try it as a directory
              options+=" --ignore-glob=${{ inputs.root-dir }}/$path/**"
          done
        fi
        if [ "${{ inputs.skip-doctests }}" != "true" ]; then
          options+=" --doctest-modules"
        fi
        
        # Run pytest with all options
        echo "Running: pytest $options ${{ inputs.root-dir }}"
        pytest $options ${{ inputs.root-dir }}
