name: Install Packages

inputs:
  pypi-packages:
    description: 'Python packages to install'
    required: false
  apt-packages:
    description: 'APT packages to install'
    required: false
  npm-packages:
    description: 'NPM packages to install'
    required: false
  dependency-files:
    description: 'Paths to dependency files. Can be a requirements.txt or a setup.cfg file'
    required: false
  test-requirements-file:
    description: "Paths to requirements files. Provide a comma separated list of paths from the current directory. '.txt' files will be pip installed. '.cfg' files will be parsed and the install_requires and tests_require sections will be installed."
    required: false
  ssh-private-key:
    description: 'SSH private key to install private packages from source, if any.'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Configure SSH
      if: ${{ inputs.ssh-private-key }}
      uses: webfactory/ssh-agent@v0.7.0
      with:
          ssh-private-key: ${{ inputs.ssh-private-key }}

    - name: Install Pypi Packages
      if: ${{ inputs.pypi-packages }}
      shell: bash
      run: |
        set -e
        if [[ "${{ inputs.pypi-packages }}" == "isee" && "${{ github.repository }}" == "i2mint/isee" ]]; then
          echo "Installing isee from source"
          python setup.py sdist
          pip install $(ls -t dist/isee-*.tar.gz 2>/dev/null | head -n 1)
        elif [[ "${{ inputs.pypi-packages }}" == "wads" && "${{ github.repository }}" == "i2mint/wads" ]]; then
          echo "Installing wads from source"
          python setup.py sdist
          pip install $(ls -t dist/wads-*.tar.gz 2>/dev/null | head -n 1)
        else
          python -m pip install --upgrade pip wheel
          pip install ${{ inputs.pypi-packages }}
        fi

    - name: Install APT Packages
      if: ${{ inputs.apt-packages }}
      shell: bash
      run: |
        set -e
        sudo apt-get update
        sudo apt-get install -y ${{ inputs.apt-packages }}

    - name: Install NPM Packages
      if: ${{ inputs.npm-packages }}
      shell: bash
      run: |
        set -e
        npm install -g ${{ inputs.npm-packages }}

    - name: Install Dependencies
      if: ${{ inputs.dependency-files }}
      shell: bash
      run: |
        set -e
        python -m pip install --upgrade pip wheel
        IFS=',' read -ra paths <<< "${{ inputs.dependency-files }}"
        for path in "${paths[@]}"
        do
          isee_installed=false
          if [[ $path == *.txt ]]; then
            pip install -r $path
          elif [[ $path == *.cfg ]]; then
            if [ "$isee_installed" == "false" ]; then
              if [ "${{ github.repository }}" == "i2mint/isee" ]; then
                echo "Installing isee from source"
                python setup.py sdist
                pip install $(ls -t dist/isee-*.tar.gz 2>/dev/null | head -n 1)
              else
                echo "Installing isee from pip"
                pip -q install isee
              fi
              isee_installed=true
            fi
            isee install-requires
            isee tests-require
          fi
        done
