name: Install Packages

inputs:
  pypi-packages:
    description: 'Python packages to install'
    required: false
  apt-packages:
    description: 'APT packages to install'
    required: false
  npm-packages:
    description: 'NPM packages to install'
    required: false
  dependency-files:
    description: 'Paths to dependency files. Can be a requirements.txt or a setup.cfg 
      file'
    required: false
  test-requirements-file:
    description: "Paths to requirements files. Provide a comma separated list of 
      paths from the current directory. '.txt' files will be pip installed. '.cfg'
      files will be parsed and the install_requires and tests_require sections will be 
      installed."
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install Pypi Packages
      if: ${{ inputs.pypi-packages }}
      run: |
        python -m pip install --upgrade pip
        pip install ${{ inputs.pypi-packages }}

    - name: Install APT Packages
      if: ${{ inputs.apt-packages }}
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ inputs.apt-packages }}

    - name: Install NPM Packages
      if: ${{ inputs.npm-packages }}
      run: npm install -g ${{ inputs.npm-packages }}

    - name: Install Dependencies
      if: ${{ inputs.dependency-files }}
      run: |
        IFS=',' read -ra paths <<< "$dependency-files"
        for path in "${paths[@]}"
        do
          isee_installed=false
          if [[ $path == *.txt ]]; then
            pip install -r $path
          elif [[ $path == *.cfg ]]; then
            if [ "$isee_installed" == "false" ]; then
              if [ "${{ github.repository }}" == "i2mint/isee" ]; then
                echo "Installing isee from source"
                python setup.py sdist
                pip install $(find dist/ -iname isee-*.tar.gz)
              else
                echo "Installing isee from pip"
                pip -q install isee
              fi
              isee_installed=true
            fi
            isee install-requires
            isee tests-require
          fi
        done
