name: Install Packages

inputs:
  python_packages:
    description: 'Python packages to install'
    required: false
  apt_packages:
    description: 'APT packages to install'
    required: false
  npm_packages:
    description: 'NPM packages to install'
    required: false
  requirements_file:
    description: 'Paths to requirements files'
    required: false
  test_requirements_file:
    description: 'Paths to requirements files'
    required: false
  use-setup-cfg:
    description: "install from setup.cfg install_requires and tests_require"
    required: false
    default: "false"

runs:
  using: 'composite'
  steps:
    - name: Install Python Packages
      if: ${{ inputs.python_packages }}
      run: |
        python -m pip install --upgrade pip
        pip install -q ${{ inputs.python_packages }}
      shell: bash

    - name: Install APT Packages
      if: ${{ inputs.apt_packages }}
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ inputs.apt_packages }}
      shell: bash

    - name: Install NPM Packages
      if: ${{ inputs.npm_packages }}
      run: |
        npm install -g ${{ inputs.npm_packages }}
      shell: bash

    - name: Install Python Requirements
      if: ${{ inputs.requirements_file }}
      run: |
        pip install -r ${{ inputs.requirements_file }}
      shell: bash
    
    - name: Install Test Requirements
      if: ${{ inputs.test_requirements_file }}
      run: |
        pip install -r ${{ inputs.test_requirements_file }}
      shell: bash
          
    - name: Install from setup.cfg
      if: ${{ inputs.use-setup-cfg }}
      run: |
        if [ "${{ github.repository }}" == "i2mint/isee" ]; then
          echo "Installing isee from source"
          python setup.py sdist
          pip install $(find dist/ -iname isee-*.tar.gz)
        else
          echo "Installing isee from pip"
          pip -q install isee
        fi
        isee install-requires
        isee tests-require
      shell: bash