name: "Version Bump"
description: "Generate semantic version and update pyproject.toml or setup.cfg"

inputs:
  config-file:
    description: "Config file to update (auto-detects pyproject.toml or setup.cfg if not specified)"
    required: false

outputs:
  version:
    description: "The generated version number"
    value: ${{ steps.gen_version.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: Install Dependencies
      shell: bash
      run: |
        set -e
        python -m pip install --upgrade pip

        # Install isee for version generation and file updates
        if [ "${{ github.repository }}" = "i2mint/isee" ]; then
          echo "Installing isee from source"
          python -m pip install -e .
        else
          python -m pip install isee
        fi

    - name: Generate Version Number
      shell: bash
      id: gen_version
      run: |
        set -e

        # Generate the new version
        VERSION=$(isee gen-semver --output-mode=print)

        # Validate the version string
        if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Invalid version format: $VERSION"
          exit 1
        fi

        # Export to GitHub environment and output
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "version=$VERSION" >> $GITHUB_OUTPUT

        echo "Generated version: $VERSION"

    - name: Update Configuration File
      shell: bash
      run: |
        set -e
        VERSION="${{ steps.gen_version.outputs.version }}"

        echo "Updating configuration file with version: $VERSION"

        # Use isee update-setup-cfg which handles both pyproject.toml and setup.cfg
        isee update-setup-cfg --version="$VERSION"
