name: "Pylint Validation"
description: "Validate source code running pylint"
inputs:
  enable:
    description: "Pylint features to enable. Provide a comma separated list of strings. 
      Example: 'C0114,C0115,C0116'. If not provided, all features are enabled.
      Documentation on 'enable' codes: 
      http://pylint.pycqa.org/en/latest/technical_reference/features.html#basic-checker-messages"
    required: false
  ignore:
    description: "Folders and or files to ignore. Provide a comma separated list of 
      strings. Any file that contains any of these strings in its path will be ignored. 
      Example: 'tests,docs,setup.py'"
    required: false
  extra-args:
    description: "Additional arguments to pass to pylint"
    required: false
runs:
  using: 'composite'
  steps:
    - name: Install Dependencies
      uses: i2mint/isee/actions/install-packages@master
      with:
        pypi-packages: 'pylint isee'

    - name: Validate Source Code
      shell: bash
      run: |
        if [ -n "${{ inputs.ignore }}" ]; then
          ignore="--ignore ${{ inputs.ignore }}"
        fi
        if [ -n "${{ inputs.enable }}" ]; then
          enable="--disable=all --enable=${{ inputs.enable }}"
        fi
        pylint . $ignore $enable ${{ inputs.extra-args }} | mk_pylint_report
