inputs:
  root-dir:
    description: "Root directory to validate. Defaults to the current directory."
    required: false
    default: "."
  enable:
    description: "Pylint features to enable. Provide a comma separated list of strings. ..."
    required: false
  ignore:
    description: "Folders and or files to ignore. Provide a comma separated list of strings. ..."
    required: false
  ignore-patterns:
    description: "Regex patterns for files/folders to ignore"
    required: false
  extra-args:
    description: "Additional arguments to pass to pylint"
    required: false
runs:
  using: 'composite'
  steps:
    - name: Install Dependencies
      uses: i2mint/isee/actions/install-packages@master
      with:
        pypi-packages: 'pylint isee'

    - name: Validate Source Code
      shell: bash
      run: |
        set -e

        # Build ignore-paths from ignore input (convert comma-separated to regex)
        if [ -n "${{ inputs.ignore }}" ]; then
          IFS=',' read -ra paths <<< "${{ inputs.ignore }}"
          ignore_paths_list=""
          for path in "${paths[@]}"; do
            path=$(echo "$path" | xargs)  # Trim whitespace
            if [ -n "$ignore_paths_list" ]; then
              ignore_paths_list+=","
            fi
            ignore_paths_list+=".*${path}.*"
          done
          ignore="--ignore-paths=$ignore_paths_list"
        fi

        # Use ignore-patterns if provided
        if [ -n "${{ inputs.ignore-patterns }}" ]; then
          ignore_patterns="--ignore-patterns=${{ inputs.ignore-patterns }}"
        fi

        if [ -n "${{ inputs.enable }}" ]; then
          enable="--disable=all --enable=${{ inputs.enable }}"
        fi

        pylint ${{ inputs.root-dir }} $ignore $ignore_patterns $enable ${{ inputs.extra-args }} | mk_pylint_report
