name: "Publish"
description: "Publish package to Pypi"
inputs:
  pypi-username:
    description: "Pypi account username"
    required: true
  pypi-password:
    description: "Pypi account password"
    required: true
  package-path:
    description: "Path to the package(s) to publish. By default, all packages in the 
      dist folder are published."
    required: false
    default: "./dist/*"
  twine-args:
    description: "Additional arguments to pass to twine. Defaults to 
      '--non-interactive --skip-existing --disable-progress-bar'. See 
      https://twine.readthedocs.io/en/latest/#twine-upload-command for more 
      information."
    required: false
    default: "--non-interactive  --skip-existing --disable-progress-bar"
runs:
  using: 'composite'
  steps:
    - name: Install Dependencies
      uses: i2mint/isee/actions/install-packages@master
      with:
        pypi-packages: 'twine'
    - name: Publish to Pypi
      shell: bash
      run: |
        twine upload ${{ inputs.package-path }} -u ${{ inputs.pypi-username }} -p ${{ inputs.pypi-password }} ${{ inputs.twine-args }} --verbose
