name: GitHub Pages
description: "Generate documentation using Epythet"
on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: i2mint/epythet/actions/publish-github-pages@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          docs-branch: "gh-pages"
          docs-dir: "./docsrc/_build/html/"
          python-version: "3.10"
