name: "Check In"
description: "Check in the repository"
inputs:
  commit-message:
    description: "Commit message"
    required: true
  args:
    description: "Arguments to pass to 'pack check-in"
    required: false
    default: "--auto-choose-default-action --bypass-docstring-validation --bypass-tests --bypass-code-formatting --verbose"
runs:
  using: composite
  steps:
    - name: Install Dependencies
      uses: i2mint/isee/actions/install-packages@master
      with:
        pypi-packages: 'wads'
    - name: Check in
      shell: bash
      run: pack check-in "${{ inputs.commit-message }}" ${{ inputs.args }}
