name: CI Diagnosis
description: "Diagnose the CI process, setup etc."

on:
  push:
    branches:
      - master

jobs:
  diagnose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # See https://graphite.dev/guides/github-actions-variables
      # GITHUB_REPOSITORY: The owner and repository name. For example, octocat/Hello-World.
      # GITHUB_REF: The branch or tag ref that triggered the workflow.
      # GITHUB_WORKSPACE: The GitHub workspace directory path.
      # GITHUB_WORKFLOW: The name of the workflow.
      # GITHUB_ACTOR: The name of the person or app that initiated the workflow.
      # GITHUB_SHA: The commit SHA that triggered the workflow.
      - name: Print GitHub environment variables
        run: |
          echo "Repository name: $GITHUB_REPOSITORY"
          echo "Branch or tag ref: $GITHUB_REF"
          echo "Workspace directory: $GITHUB_WORKSPACE"
          echo "Workflow name: $GITHUB_WORKFLOW"
          echo "Actor (user or app): $GITHUB_ACTOR"
          echo "Commit SHA: $GITHUB_SHA"