name: "Bump verison number"
description: "Bump the version number in setup.cfg and save it to the environment 
  variable VERSION"
runs:
  using: 'composite'
  steps:
    - name: Install Dependencies
      uses: i2mint/isee/actions/install-packages@master
      with:
        pypi-packages: 'isee'
    - name: Update version number
      shell: bash
      run: |
        set -e
        export VERSION=$(isee gen-semver)
        # export VERSION=$(echo $(isee gen-semver))
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        isee update-setup-cfg
