name: Continuous Integration
on: [push, pull_request]
env:
  PROJECT_NAME: isee
jobs:
  validation:
    name: Validation
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: i2mint/isee/actions/validation@master
        with:
          PROJECT_NAME: ${{ env.PROJECT_NAME }}
          python-version: ${{ matrix.python-version }}
          pytest-enable: false
          use-setup-cfg: true

  publish:
    name: Publish
    if: "!contains(github.event.head_commit.message, '[skip ci]') && github.ref == 'refs/heads/master'"
    needs: validation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: i2mint/isee/actions/publish@master
        with:
          PROJECT_NAME: ${{ env.PROJECT_NAME }}
          python-version: ${{ matrix.python-version }}
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

  github-pages:
    name: Publish GitHub Pages
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: i2mint/epythet/actions/publish-github-pages@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
