name: Test Action Workflow

on:
  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  test_default_branch:
    runs-on: ubuntu-latest
    name: Make sure the action works
    steps:
      - uses: actions/checkout@v2

      - id: default-branch
        uses: thorwhalen/get-the-default-branch-action@v1

      - if: ${{ steps.default-branch.outputs.default_branch == 'master' }}
        run: echo "Success! The default branch is in fact 'master'!"
        
  print_env_variables:
    runs-on: ubuntu-latest
    name: Validation
    steps:
      - uses: i2mint/isee/actions/ci-diagnosis@master
