name: Test Action Workflow

on:
  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  test_default_branch:
    runs-on: ubuntu-latest
    name: Make sure the action works
    steps:
      - uses: actions/checkout@v2

      - id: default-branch
        uses: scottmmjackson/get-the-default-branch-action@v1

      - if: ${{ steps.default-branch.outputs.default_branch == 'master' }}
        run: echo "Success! The default branch is in fact 'master'!"
        
  print_env_variables:

    name: Validation
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:

      - uses: i2mint/isee/actions/ci-diagnosis@master
